### PR TITLE
fix: update to unzip-stream

### LINKED ISSUE #24: unzip dependency is outdated
When installing `ipfs-desktop` I got a warning (among others) about an outdated version of `graceful-fs` (see https://github.com/nodejs/node/issues/5213 ). It comes from the package `unzip` that this package depends upon. There exists https://github.com/mhr3/unzip-stream/ - which seems to address this situation, however I have not yet done any testing.

Here is the breakdown of the npm install warning

```
ipfs-desktop@0.3.0 (graceful-fs)
└─┬ ipfsd-ctl@0.26.0
  └─┬ go-ipfs-dep@0.4.13
    └─┬ unzip@0.1.11 # is the latest version (and three years old, btw.)
      └─┬ fstream@0.1.31 # is currently at v1.0.11 (and deps on graceful ^4.1.2)
        └── graceful-fs@3.0.11 # other modules dedup to graceful-fs@4.1.11
```

### PR DESCRIPTION
**Pull request by hacdias**
Fixes #24

### CODE REVIEW

**Comment by hacdias** [comment]
@VictorBjelkholm just like we did in `npm-go-ipfs`, should we move this to Jenkins only? 😄 This doesn't use Aegir either.

**Comment by VictorBjelkholm** [comment]
@hacdias sure! I'll remove CircleCI and TravisCI and you can add the Jenkinsfile, as soon as it's there, Jenkins should pick up the job automatically.

**Comment by VictorBjelkholm** [comment]
Ok, circle + travis has been disabled!

**Comment by hacdias** [comment]
Thanks @VictorBjelkholm

**Pull request merged**
