### PR TITLE
tools: Add Makefile

### PR DESCRIPTION
**Pull request by haadcode**
This PR will add a Makefile to the repo.

Started from this discussion (read it through): https://github.com/ipfs/go-ipfs-dep/pull/13#discussion_r90838240.

### CODE REVIEW

**Comment by diasdavid** [comment]
Makefiles don't work in windows, npm scrips do, can these be npm scripts?

**Comment by haadcode** [comment]
@diasdavid See the discussion linked in the first comment, the reasoning, pros and cons are laid out there.

tl;dr: The idea is not to make Makefiles the primary build tool but more of an additional entry point / documentation for WHICH npm commands the use should run.

**Comment by diasdavid** [comment]
Closing this one. We won't be replacing npm scripts by Makefile on this repo. Thanks for the PR eitherway :)

**Comment by thisconnect** [comment]
Thanks @diasdavid

**Pull request closed without merging**
